title: 'Ticket Chief: An HTTP server from scratch'
date: today
author:
  name: Andromeda
  affiliation: Hack Club

project:
  render:
    - report.md
format:
  html:
    theme: litera
    embed-resources: true

toc: true
highlight-style: atom-one
